all: clear compile run1 echo1 run2

compile:

	@g++-11 driver2.cpp -o d2.out
	@g++-11 driver1.cpp -o d1.out

run1:
	@./d1.out
	
echo1:

	@echo "TEST FONKSIYONU BASARIYLA BITTI DRIVER 2 YE GECIS YAPILIYOR"
	
run2:

	@./d2.out

clear:

	@clear
